apiVersion: apps/v1
kind: Deployment
metadata:
  name: postman-master
  namespace: postman-testing
  labels:
    app: postman-testing
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postman-testing
  template:
    metadata:
      labels:
        app: postman-testing
    spec:
      containers:
        - name: postman-testing
          image: slobodang/jenkins-postman-slave:latest
          ports:
            - containerPort: 22
