apiVersion: apps/v1
kind: Deployment
metadata:
  name: postman-master
  namespace: postman
  labels:
    app: postman
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postman
  template:
    metadata:
      labels:
        app: postman
    spec:
      containers:
        - name: nginx
          image: slobodang/jenkins-postman-slave:latest
          ports:
            - containerPort: 22
