pipeline {
    agent any

    stages {
        stage('Build') {
            agent {
                label 'jenkins-docker-slave'
            }
            steps {
                sh '''
                    ls -la
                    node --version
                    npm --version
                    npm install
                    npm run build
                    ls -la
                '''
            }
        }
    }
}
