pipeline {
    agent any

    stages {
        stage('Build') {
            agent {
                label 'jenkins-docker-slave'
            }
            steps {
                sh '''
                    ls -la
                    node --version
                    npm --version
                    cd learn-jenkins
                    npm ci
                    npm run build
                    ls -la
                '''
            }
        }
        stage('Test') {
            agent {
                label 'jenkins-docker-slave'
            }
            steps {
                sh '''
                    echo "Running tests..."
                    cd learn-jenkins
                    npm test
                    cd build
                    test -f index.html
                '''
            }
        }
    }
}
