pipeline {
    agent any

    stages {
        /*
        stage('Build') {
            agent {
                label 'jenkins-docker-slave'
            }
            steps {
                sh '''
                    ls -la
                    node --version
                    npm --version
                    cd learn-jenkins
                    npm ci
                    npm run build
                    ls -la
                '''
            }
        }
        */
        stage('Test') {
            agent {
                label 'jenkins-docker-slave'
            }
            steps {
                sh '''
                    echo "Running tests..."
                    #cd build
                    #test -f index.html
                    cd learn-jenkins
                    npm test
                '''
            }
        }
                stage('E2E') {
            agent {
                label 'jenkins-docker-slave'
            }
            steps {
                sh '''
                    npm install -g playwright
                    npm install -g serve
                    serve -s build
                    npx playwright test
                '''
            }
        }
    }
    
    post {
        always {
            junit 'learn-jenkins/test-results/junit.xml'
        }
    }
}
