apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker-slave
  namespace: docker-staging
  labels:
    app: docker-staging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: docker-staging
  template:
    metadata:
      labels:
        app: docker-staging
    spec:
      containers:
        - name: jenkins-staging
          image: slobodang/jenkins-docker-slave:latest
          ports:
            - containerPort: 22
