---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: apps-staging
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/slobodangrbic/jenkins-agents-nginx-ssl.git
    targetRevision: HEAD
    path: argo-helm/environments/staging/apps
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true 
      allowEmpty: true
    syncOptions:
    - CreateNamespace=true
    - Validate=true
    - PruneLast=true
    - PrunePropagationPolicy=Foreground