apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-master
  namespace: jenkins-staging
  labels:
    app: jenkins-staging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins-staging
  template:
    metadata:
      labels:
        app: jenkins-staging
    spec:
      containers:
        - name: jenkins-staging
          image: slobodang/jenkins-master:latest
          ports:
            - containerPort: 8080
