apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker-slave
  namespace: docker-dev
  labels:
    app: docker-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: docker-dev
  template:
    metadata:
      labels:
        app: docker-dev
    spec:
      containers:
        - name: docker-dev
          image: slobodang/jenkins-docker-slave:latest
          ports:
            - containerPort: 22
