apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker-slave
  namespace: docker
  labels:
    app: docker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: docker
  template:
    metadata:
      labels:
        app: docker
    spec:
      containers:
        - name: nginx
          image: slobodang/jenkins-docker-slave:latest
          ports:
            - containerPort: 22
